### PR TITLE
change validate signature with hmac validation

### PR DESCRIPTION
**Pull request by gmbelart**
based on this
https://docs.shopify.com/api/authentication/oauth#verification

MD5 Signature Validation will be removed after June 1st, 2016

### CODE REVIEW

**Comment by omarel1** [comment]
Oh wow, is the file already updated. Or do we need to update that
individually?

**Comment by gmbelart** [comment]
not yet, you can check my update on validate signature function on my repo.

**Comment by cmcdonaldca** [comment]
I'll trust that this works ;-)

**Comment by omarel1** [comment]
Just tried it. It authenticates properly for me.

Only thing is I noticed some syntax errors pointed out by my text editor, but couldn't

 pin point the issue.

**Comment by gmbelart** [comment]
@omarel1 hmm, do you know what's wrong?
or maybe it because I use short array syntax [] instead of array()? (php >= 5.4)
I just noticed that minimum requirement of this script is php 4

@omarel1 please update your script with this 
```
$dataString = array();
		foreach ($query as $key => $value) {
			if(!in_array($key, array('shop', 'timestamp', 'code'))) continue;
```
and let me know if the error still exists or not? if the error is gone, I'll update my remo and make another pull request.
how do you think @cmcdonaldca ?

**Comment by omarel1** [comment]
Yes that removed the syntax error and the validation still worked. Thank
you.

**Comment by gmbelart** [comment]
@omarel1 check my pull request #14 
I change hash_hmac function too because hash_hmac need php >= 5.1.2

```php
    public function validateSignature($query)
	{
		if(!is_array($query) || empty($query['hmac']) || !is_string($query['hmac']))
			return false;

		$dataString = array();
		foreach ($query as $key => $value) {
			if(!in_array($key, array('shop', 'timestamp', 'code'))) continue;

			$key = str_replace('=', '%3D', $key);
			$key = str_replace('&', '%26', $key);
			$key = str_replace('%', '%25', $key);

			$value = str_replace('&', '%26', $value);
			$value = str_replace('%', '%25', $value);

			$dataString[] = $key . '=' . $value;
		}
		sort($dataString);
		
		$string = implode("&", $dataString);

		$signatureBin = mhash(MHASH_SHA256, $string, $this->secret);
		$signature = bin2hex($signatureBin);
		
		return $query['hmac'] == $signature;
	}
```

**Pull request merged**
